import { Jockey_One, Baloo_Bhaijaan_2 } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

const jockeyOne = Jockey_One({
  variable: "--font-jockey-one",
  subsets: ["latin"],
  weight: "400",
});

const balooBhaijaan2 = Baloo_Bhaijaan_2({
  variable: "--font-baloo-bhaijaan-2",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body className={`${balooBhaijaan2.variable} ${jockeyOne.variable} !font-baloo-bhaijaan-2 antialiased`}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
