import { Jockey_One, Baloo_Bhaijaan_2 } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import AudioPlayer from "./components/audio_player";

const jockeyOne = Jockey_One({
  variable: "--font-jockey-one",
  subsets: ["latin"],
  weight: "400",
});

const balooBhaijaan2 = Baloo_Bhaijaan_2({
  variable: "--font-baloo-bhaijaan-2",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body
        className={`${balooBhaijaan2.variable} ${jockeyOne.variable} !font-baloo-bhaijaan-2 antialiased`}
      >
        
        <AudioPlayer>
          {children}
        </AudioPlayer>
      </body>
    </html>
  );
}
